//! Minimal in-place OLE container. COM ownership/refcounts are generated by windows-rs.
use super::dispatch::Value;
use std::rc::Rc;
use windows::{
    core::*,
    Win32::{
        Foundation::*,
        System::{Com::*, Ole::*, Variant::*},
        UI::WindowsAndMessaging::*,
    },
};

#[implement(IOleInPlaceFrame)]
struct Frame(HWND);
impl IOleWindow_Impl for Frame {
    fn GetWindow(&self) -> Result<HWND> {
        Ok(self.0)
    }
    fn ContextSensitiveHelp(&self, _: BOOL) -> Result<()> {
        Err(E_NOTIMPL.into())
    }
}
impl IOleInPlaceUIWindow_Impl for Frame {
    fn GetBorder(&self) -> Result<RECT> {
        Ok(rect(self.0))
    }
    fn RequestBorderSpace(&self, _: *const RECT) -> Result<()> {
        Err(INPLACE_E_NOTOOLSPACE.into())
    }
    fn SetBorderSpace(&self, _: *const RECT) -> Result<()> {
        Ok(())
    }
    fn SetActiveObject(&self, _: Option<&IOleInPlaceActiveObject>, _: &PCWSTR) -> Result<()> {
        Ok(())
    }
}
impl IOleInPlaceFrame_Impl for Frame {
    fn InsertMenus(&self, _: HMENU, _: *mut OLEMENUGROUPWIDTHS) -> Result<()> {
        Err(E_NOTIMPL.into())
    }
    fn SetMenu(&self, _: HMENU, _: isize, _: HWND) -> Result<()> {
        Ok(())
    }
    fn RemoveMenus(&self, _: HMENU) -> Result<()> {
        Ok(())
    }
    fn SetStatusText(&self, _: &PCWSTR) -> Result<()> {
        Ok(())
    }
    fn EnableModeless(&self, _: BOOL) -> Result<()> {
        Ok(())
    }
    fn TranslateAccelerator(&self, _: *const MSG, _: u16) -> Result<()> {
        Err(S_FALSE.into())
    }
}

#[implement(IOleClientSite, IOleInPlaceSite, IOleControlSite, IDispatch)]
struct Site {
    hwnd: HWND,
    frame: IOleInPlaceFrame,
    _sta: Rc<()>,
}
pub fn client_site(hwnd: HWND, frame_hwnd: HWND) -> IOleClientSite {
    Site {
        hwnd,
        frame: Frame(frame_hwnd).into(),
        _sta: Rc::new(()),
    }
    .into()
}
pub fn rect(hwnd: HWND) -> RECT {
    let mut r = RECT::default();
    unsafe {
        let _ = GetClientRect(hwnd, &mut r);
    }
    r
}
impl IOleClientSite_Impl for Site {
    fn SaveObject(&self) -> Result<()> {
        Err(E_NOTIMPL.into())
    }
    fn GetMoniker(&self, _: &OLEGETMONIKER, _: &OLEWHICHMK) -> Result<IMoniker> {
        Err(E_NOTIMPL.into())
    }
    fn GetContainer(&self) -> Result<IOleContainer> {
        Err(E_NOINTERFACE.into())
    }
    fn ShowObject(&self) -> Result<()> {
        Ok(())
    }
    fn OnShowWindow(&self, _: BOOL) -> Result<()> {
        Ok(())
    }
    fn RequestNewObjectLayout(&self) -> Result<()> {
        Err(E_NOTIMPL.into())
    }
}
impl IOleWindow_Impl for Site {
    fn GetWindow(&self) -> Result<HWND> {
        Ok(self.hwnd)
    }
    fn ContextSensitiveHelp(&self, _: BOOL) -> Result<()> {
        Err(E_NOTIMPL.into())
    }
}
impl IOleInPlaceSite_Impl for Site {
    fn CanInPlaceActivate(&self) -> Result<()> {
        Ok(())
    }
    fn OnInPlaceActivate(&self) -> Result<()> {
        Ok(())
    }
    fn OnUIActivate(&self) -> Result<()> {
        Ok(())
    }
    fn GetWindowContext(
        &self,
        frame: *mut Option<IOleInPlaceFrame>,
        doc: *mut Option<IOleInPlaceUIWindow>,
        pos: *mut RECT,
        clip: *mut RECT,
        info: *mut OLEINPLACEFRAMEINFO,
    ) -> Result<()> {
        if frame.is_null() || doc.is_null() || pos.is_null() || clip.is_null() || info.is_null() {
            return Err(E_POINTER.into());
        }
        unsafe {
            frame.write(Some(self.frame.clone()));
            doc.write(None);
            pos.write(rect(self.hwnd));
            clip.write(rect(self.hwnd));
            info.write(OLEINPLACEFRAMEINFO {
                cb: std::mem::size_of::<OLEINPLACEFRAMEINFO>() as u32,
                fMDIApp: false.into(),
                hwndFrame: self.frame.GetWindow()?,
                haccel: HACCEL::default(),
                cAccelEntries: 0,
            });
        }
        Ok(())
    }
    fn Scroll(&self, _: &SIZE) -> Result<()> {
        Err(E_NOTIMPL.into())
    }
    fn OnUIDeactivate(&self, _: BOOL) -> Result<()> {
        Ok(())
    }
    fn OnInPlaceDeactivate(&self) -> Result<()> {
        Ok(())
    }
    fn DiscardUndoState(&self) -> Result<()> {
        Ok(())
    }
    fn DeactivateAndUndo(&self) -> Result<()> {
        Ok(())
    }
    fn OnPosRectChange(&self, _: *const RECT) -> Result<()> {
        Ok(())
    }
}
impl IOleControlSite_Impl for Site {
    fn OnControlInfoChanged(&self) -> Result<()> {
        Ok(())
    }
    fn LockInPlaceActive(&self, _: BOOL) -> Result<()> {
        Ok(())
    }
    fn GetExtendedControl(&self) -> Result<IDispatch> {
        Err(E_NOTIMPL.into())
    }
    fn TransformCoords(&self, _: *mut POINTL, _: *mut POINTF, _: &XFORMCOORDS) -> Result<()> {
        Err(E_NOTIMPL.into())
    }
    fn TranslateAccelerator(&self, _: *const MSG, _: KEYMODIFIERS) -> Result<()> {
        Err(S_FALSE.into())
    }
    fn OnFocus(&self, _: BOOL) -> Result<()> {
        Ok(())
    }
    fn ShowPropertyFrame(&self) -> Result<()> {
        Err(E_ACCESSDENIED.into())
    }
}
impl IDispatch_Impl for Site {
    fn GetTypeInfoCount(&self) -> Result<u32> {
        Ok(0)
    }
    fn GetTypeInfo(&self, _: u32, _: u32) -> Result<ITypeInfo> {
        Err(E_NOTIMPL.into())
    }
    fn GetIDsOfNames(
        &self,
        _: *const GUID,
        _: *const PCWSTR,
        _: u32,
        _: u32,
        _: *mut i32,
    ) -> Result<()> {
        Err(DISP_E_UNKNOWNNAME.into())
    }
    fn Invoke(
        &self,
        id: i32,
        _: *const GUID,
        _: u32,
        _: DISPATCH_FLAGS,
        _: *const DISPPARAMS,
        out: *mut VARIANT,
        _: *mut EXCEPINFO,
        _: *mut u32,
    ) -> Result<()> {
        if out.is_null() {
            return Err(E_POINTER.into());
        }
        let value = match id {
            -709 => Value::boolean(true), // DISPID_AMBIENT_USERMODE
            -710 | -711 | -712 | -713 => Value::boolean(false),
            _ => return Err(DISP_E_MEMBERNOTFOUND.into()),
        };
        unsafe {
            out.write(value.into_raw());
        }
        Ok(())
    }
}
